#! /bin/bash

show_help () {
    echo "Usage: $0 <bash_script_to_walk_through>"
    exit 0
}

echo_run () {
    str=$1
    while read -p '>' < /dev/tty && [ "$REPLY" ]; do
        eval "$REPLY"
    done
    if [[ $str != " "* ]]; then
        echo -n '> '
        for (( i=0; i<${#str}; i++ )); do
          echo -n "${str:$i:1}"
          sleep 0.02
        done
        echo ''
    fi
    eval $1
}

if [ "$1" ]; then
    if [ -f "$1" ]; then
        while IFS='' read -r line || [[ -n "$line" ]]; do
            if [ "$line" ]; then
                echo_run "$line"
            fi
        done < "$1"
    else
        echo "Cannot find file: $1"
        exit 1
    fi
else
    show_help
    exit 0
fi

